using System; using System.IO; using System.Reflection; using System.Runtime.CompilerServices;
public class CacheProxy : DispatchProxy { public static bool Saved; protected override object Invoke(MethodInfo method, object[] args) { if (method.IsGenericMethod && method.GetGenericArguments()[0] == typeof(bool)) return Saved; return null; } }
class RuntimeProbe {
static void Check(string root,string file,string typeName,string method,object expected){var assembly=Assembly.LoadFrom(Path.Combine(root,file)); var type=assembly.GetType(typeName,true); var target=RuntimeHelpers.GetUninitializedObject(type); object value=type.GetMethod(method,BindingFlags.Public|BindingFlags.NonPublic|BindingFlags.Instance).Invoke(target,null);if(!value.Equals(expected))throw new Exception(typeName+"."+method+" mismatch: "+value); Console.WriteLine("PASS runtime "+typeName+"."+method+" = "+value);}
static int Main(string[]a){string root=a[0];
foreach(string type in new[]{"AuthenticatedStatisticalEventSender","UnauthenticatedStatisticalEventSender"})foreach(string method in new[]{"get_CanSendTelemetryEvents","get_IsShareStatisticsEnabled"})Check(root,"ProtonVPN.StatisticalEvents.dll","ProtonVPN.StatisticalEvents.Events.Senders."+type,method,false);
Check(root,"ProtonVPN.Client.Logic.Connection.dll","ProtonVPN.Client.Logic.Connection.ChangeServerModerator","CanChangeServer",true); Check(root,"ProtonVPN.Client.Logic.Connection.dll","ProtonVPN.Client.Logic.Connection.ChangeServerModerator","GetRemainingDelayUntilNextAttempt",TimeSpan.Zero);
Check(root,"ProtonVPN.Client.dll","ProtonVPN.Client.UI.Main.Sidebar.Connections.Profiles.ProfilesPageViewModel","get_IsUpsellBannerVisible",false);
Check(root,"ProtonVPN.Client.dll","ProtonVPN.Client.UI.Main.Features.NetShield.NetShieldWidgetViewModel","get_IsRestricted",false);
Check(root,"ProtonVPN.Client.dll","ProtonVPN.Client.UI.Main.Features.SplitTunneling.SplitTunnelingWidgetViewModel","get_IsRestricted",false);
Check(root,"ProtonVPN.Client.dll","ProtonVPN.Client.UI.Main.Settings.Pages.AdvancedSettingsPageViewModel","get_IsPaidUser",true);
var settingsAssembly=Assembly.LoadFrom(Path.Combine(root,"ProtonVPN.Client.Settings.dll")); var settingsType=settingsAssembly.GetType("ProtonVPN.Client.Settings.UserSettings",true); var settingsTarget=RuntimeHelpers.GetUninitializedObject(settingsType); var cacheField=settingsType.GetField("_userCache",BindingFlags.NonPublic|BindingFlags.Instance); cacheField.SetValue(settingsTarget,DispatchProxy.Create(cacheField.FieldType,typeof(CacheProxy))); var plan=settingsType.GetProperty("VpnPlan").GetValue(settingsTarget); if((bool)plan.GetType().GetProperty("IsPaid").GetValue(plan))throw new Exception("Test account must remain free"); Console.WriteLine("PASS runtime account plan remains free"); foreach(bool saved in new[]{false,true}) {CacheProxy.Saved=saved; foreach(string property in new[]{"IsLocalAreaNetworkAccessEnabled","IsCustomDnsServersEnabled","IsNetShieldEnabled","IsSplitTunnelingEnabled"}) {object value=settingsType.GetProperty(property).GetValue(settingsTarget); if(!(bool)value.Equals(saved))throw new Exception(property+" did not use saved value"); Console.WriteLine("PASS runtime saved "+property+" = "+saved);}} Console.WriteLine("19 runtime method checks passed; no login or VPN connection was started."); return 0;}}
